### ISSUE TITLE
Add Wing 6 Bosses

### ISSUE THREAD

**Issue by merforga** [GW2Raidar/gw2raidar#320]
First two will be interesting since..well..they're multi part bosses which I don't think we've catered for before? Closest I can think of is Xera with her two different IDs so at the very least we can group them together. Will probably want to look at tracking Nikare and Kenut seperately potentially. 

Priority is single phase parsing first and implementing Phases after

### Conjured Amalgamate:
- Conjured Amalgamate [0xabc6]
- Left Arm [0x9258]
- Right Arm [0x279e]
Notes: CA it self doesn't need to fully die (our attempt it still had like 4% hp). So I think we need to combine the above three entities when looking at DPS / kill times. Phases should be: 

1 Arm Dead
Orb Collection
Sweep
Other Arm Dead
Orb Collection
Sweep
1 Arm Dead
Orb Collection
Sweep
Other Arm Dead / till finish / reward chest

CM = If there is a sceptre spawn as well.

**Nikare and Kenut**
- Nikare : [0x5271]
- Kenut: [0x5261]

Phases
Nikare 50%
Kenut 50%
Nikare and Kenut 25% [They split here so I dunno if we want to track each entity seperately or only determine phase when BOTH are at 25%]
Nikare and Kenut Dead

**Qadim: [0x51C6]**

[W6 Logs.zip](https://github.com/GW2Raidar/gw2raidar/files/2399006/W6.Logs.zip)

[20180919-221959-CA Norm.evtc.zip](https://github.com/GW2Raidar/gw2raidar/files/2399487/20180919-221959-CA.Norm.evtc.zip)

[20180919-234005 - Qadim Norm.evtc.zip](https://github.com/GW2Raidar/gw2raidar/files/2399591/20180919-234005.-.Qadim.Norm.evtc.zip)

Other NPC ids
https://pastebin.com/gNxsvBRA

**Comment by deltaconnected** [comment]
Just a heads up, CA is a gadget and I don't know how reliable my gadget pseudo-ID gen is. Being pseudo there's also no guarantee that there isn't already a character NPC with that ID in the game so may want to consider somehow splitting the two. If there's anything missing statechange-wise or something lemme know - it's a lot of fresh code tacked on an ancient system

**Comment by immortius** [comment]
It looks like the CA boss id is actually 0xFFFFABC6 (and likewise, the arms are 0xFFFFxxxx). This is workable, just noting the discrepancy.

**Comment by immortius** [comment]
Found some funkiness in raidar's parsing of larger professions (we were mapping to int32 rather than uint32) which was causing issues.

**Comment by immortius** [comment]
I... hadn't realised CA was vulnerable during orb phase. This means that orb + sweep + post burn can basically be treated as a single phase potentially. Otherwise I'ld give the orb + sweep a fixed length, but stopping early if a damage threshold is reached as usual.

**Comment by merforga** [comment]
Sounds good re CA phasing if we simplify it to that. I'm not sure what the phase % are though  =x.

**Comment by merforga** [comment]
CM logs:
[20180921-160008 Largos Twins CM.evtc.zip](https://github.com/GW2Raidar/gw2raidar/files/2409267/20180921-160008.Largos.Twins.CM.evtc.zip)
[Uploading 20180920-220956 Qadim CM.evtc.zip…]()
[Uploading 20180919-223254 - CA CM.evtc.zip…]()

**Comment by merforga** [comment]
Alright thanks for the heads up. It seems to be ok at the moment. Will keep an eye out for any anomolies
