### ISSUE TITLE
Treating .zevtc the same as .evtc.zip (edit: not evtz)

### ISSUE THREAD

**Issue by deltaconnected** [GW2Raidar/gw2raidar#321]
to make it possible to associate the type in Windows for local stuff. Doable in a ninja edit? (would be part of next build so a week ish if anything)

**Comment by merforga** [comment]
It should be relatively easy to do. Do you have a sample file we can use to test?

**Comment by deltaconnected** [comment]
Don't have anything recent but it'd just be changing the extension, eg. http://deltaconnected.com/arcdps/20181119-214649.zevtc

(zevtc looks a bit nicer after a night of sleep, but if it's already been started as evtz I don't mind)

**Comment by merforga** [comment]
zevtc should be processed now, however there's another process blocking the upload of a file with extension zevtc so I need to find that first before this will work =x.

**Comment by merforga** [comment]
6916de3 Version 2.3.0 released on 2018-12-01 01:33:17
