### ISSUE TITLE
This repo is not accessible from the site

### ISSUE THREAD

**Issue by ajrdesign** [GW2Raidar/gw2raidar#322]
This is a pretty easy one for me to implement and hopefully get more people resources for the site. I'd suggest adding something to the Help page but I'll let @merforga handle what that would be.

I added it in two places for now:
- Footer
- During the loading screen

**Comment by ajrdesign** [comment]
Branch with changes: https://github.com/GW2Raidar/gw2raidar/tree/open-source-links

**Comment by merforga** [comment]
Do you have a screenshot? =)

**Comment by ajrdesign** [comment]
Ya here ya go: https://d.pr/free/i/cq8myb

**Comment by merforga** [comment]
@tomhalstead this one should be able to be merged straight in. See if you can and push to UAT when you have the time.

**Comment by merforga** [comment]
Looks good _b

**Comment by merforga** [comment]
Version 2.3.1 released on 2018-12-11 10:54:51
