### ISSUE TITLE
Cater for new SOI Behaviour

### ISSUE THREAD

**Issue by merforga** [GW2Raidar/gw2raidar#325]
> deltaconnectedYesterday at 9:50 AM
> "buff duration change" (aka soi) are treated as 0src/server > dst buffapplies where is_offcycle is nonzero, value is the duration extended, and overstack is the new duration of the stack changed. for simulation purposes it just extends any stack that's ticking at the time

Basically need to calculate uptimes based on extended duration as well field. Maybe need to split between old and new version of arc? I dunno.

**Comment by merforga** [comment]
deltaconnectedToday at 6:14 PM
it probably messes with how you handle overstack
not by a lot because extension isnt affected by concentration*(edited)
fast bandaid is to handle it like if (is_offcycle) BuffSimulationClass->GetCurrentTicking(quickness).timeremaining += value, else {...}
long bandaid probably what EI did and give a "source undetectable duration extension" component to incoming (with nothing to generation because undetectable)
also enabled singlestack removes unconditionally instead of just stability so logs may be a bit beefier

**Comment by immortius** [comment]
Hmm, the log I'm looking at has no buff events that are offcycle with value > 0.

**Comment by merforga** [comment]
Version 2.3.3 released on 2018-12-23 11:09:59
