### ISSUE TITLE
Require minimum health at start of logs

### ISSUE THREAD

**Issue by VoidWhisperer** [GW2Raidar/gw2raidar#336]
There's a fairly persistent issues of logs being uploaded and appearing on the top of the leaderboard when it is obvious that they were started at less than max health, as the log has a significantly lower time than other logs, despite having 1/2 to 1/3 of the DPS.

This issue has been brought up in the discord a few times.

**Comment by merforga** [comment]
Sample log
[20190209-235249 Bugged MO.evtc.zip](https://github.com/GW2Raidar/gw2raidar/files/2902709/20190209-235249.Bugged.MO.evtc.zip)

**Comment by merforga** [comment]
Version 2.3.5 released on 2019-02-27 16:43:47
