### ISSUE TITLE
Django Breaking Code Updates

### ISSUE THREAD

**Issue by anewhomegw2** [GW2Raidar/gw2raidar#359]
The source code needs a bug-fix:  'django.contrib.staticfiles' : needs to be modified to : django.templatetags.static | applies to settings.py / views.py.

The other change which is required in the \api_v2\views.py file:
'from rest_framework.schemas.inspectors import AutoSchema' line 4 needs to be change to:
'from rest_framework.schemas.coreapi import AutoSchema'

This is just to get it to compile - this removes the [staticfiles] part of the manage.py - so the code may need to be looked at it get this fully functional again.

**Comment by merforga** [comment]
Fixed in recent merge
